# Include a Weblogic 10.3.6 server for deployments

apiVersion: v1
kind: Pod
metadata:
  name: jdev
  labels:
    name: weblogic11
spec:
  containers:
  - name: jdev
    image: summersillk/acesdevtest:version1.2
    resources:
      limits:
        memory: '128Mi'
        cpu: '500m'
    ports:
      - containerPort: 7000

