apiVersion: serving.knative.dev/v1alpha1 # Current version of Knative
kind: Service
metadata:
  name: compiler
  namespace: default 
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: summersillk/acesdevtest:version1.1
            env:
              - name: appOut
                value: "Weblogic 10.3.6"