# Displays how to pull a resource for a CI/CD Pipeline within Kubernetes, Knative, and Tekton
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: aces-fos-repo-resource
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://bitbucket.di2e.net/scm/aces/